//! Headless GitHub repository-workflow client for karet.
//!
//! The crate owns GitHub URL parsing, authentication discovery, stable domain
//! models, and the public REST transport. Wire types for operations spargen can
//! represent are generated from the vendored official OpenAPI description;
//! rejected operations use reviewed typed adapters in [`GitHubClient`]. No
//! presentation dependency enters this crate.

mod client;
// The official OpenAPI document and reviewed operation manifests are filtered
// and generated by build.rs. No generated Rust lives in the source tree.
// spargen#48 tracks strict-lint failures in the embedded support runtime; keep
// those temporary exceptions at this generated-module boundary only.
#[allow(missing_docs, clippy::collapsible_if, clippy::expect_used)]
mod generated {
    include!(concat!(env!("OUT_DIR"), "/github-generated.rs"));
}
mod models;
mod remote;

pub use client::AuthSource;
pub use client::AuthState;
pub use client::GitHubClient;
pub use client::GitHubError;
pub use models::CheckRun;
pub use models::Comment;
pub use models::DependencySummary;
pub use models::IssueDetail;
pub use models::IssueFieldInput;
pub use models::IssueFieldInputValue;
pub use models::IssueSummary;
pub use models::Label;
pub use models::NewIssue;
pub use models::NewPullRequest;
pub use models::Page;
pub use models::PullRequestCommit;
pub use models::PullRequestSummary;
pub use models::RateLimit;
pub use models::TimelineEvent;
pub use models::User;
pub use models::Workflow;
pub use models::WorkflowRun;
pub use remote::GitHubRemote;
pub use remote::RepositoryIdentity;
pub use remote::parse_remote;

/// GitHub's verification verdict for a commit signature.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Verification {
    /// Whether GitHub considers the signature verified.
    pub verified: bool,
    /// GitHub's machine-readable verification reason.
    pub reason: String,
    /// Login attributed to the commit, when present.
    pub signer: Option<String>,
}
